### ISSUE TITLE
Rebalance class status progress message

### ISSUE THREAD

**Issue by nushib** [microsoft/responsible-ai-toolbox-mitigations#42]
The Rebalance class status message contains a string related to imputation instead:

No columns specified for imputation. These columns have been automatically identified:
[]
Running oversampling...

**Comment by mrfmendonca** [comment]
This is actually an expected behavior. What happening here is that some classes have a default pre-processing pipeline. For the Rebalance class, for example, when using SMOTE (which doesn't work with categorical variables or missing values), the ``transform_pipe`` parameter must contain an encoder and an imputer. Otherwise, a default ``BasicImputer`` and ``EncoderOHE`` objects are created and inserted in the ``transform_pipe`` internal variable. When calling the rebalance method, the ``BasicImputer`` and ``EncoderOHE`` will run before running SMOTE. This message is printed by the BasicImputer created. You can suppress this message by setting ``verbose = False`` when instantiating the ``Rebalance`` class
